import 'package:flutter_code_editor/flutter_code_editor.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:highlight/languages/cpp.dart';
import 'package:structogrammar/models/struct.dart';


class CodeNotifier extends Notifier<CodeController> {
  @override
  CodeController build() {
    return CodeController(language: cpp, text: "");
  }

  void generate(Struct struct) {
    String generatedCode = "// Code generated by structogrammar \n\n\n";
    String getCodeFromStruct(Struct struct) {
      String code = "";
      switch (struct.type) {
        case StructType.instruction:
          return (struct.data["instruction"] ?? "").toString();
        case StructType.ifSelect:
          code = "if (${struct.data["condition"]}) \n\t\t{";
          List<Struct> trueStructs = struct.subStructs.where((e) => e.data["ifValue"] == true).toList();
          List<Struct> falseStructs = struct.subStructs.where((e) => e.data["ifValue"] == false).toList();
          for (int i = 0; i < trueStructs.length; i++) {
            code += "\n\t\t\t${getCodeFromStruct(trueStructs[i])}";
          }
          code += "\n\t\t}";
          String elseCode = "";
          for (int i = 0; i < falseStructs.length; i++) {
            elseCode += "\n\t\t\t${getCodeFromStruct(falseStructs[i])}";
          }
          if (elseCode.replaceAll("\n", "").replaceAll("\t", "").isNotEmpty) {
            code += " else \n\t\t{";
            code += elseCode;
            code += "\n\t\t}";
          }
          return code;
        case StructType.loop:
          code = "${struct.data["loopType"] ?? ""} (${struct.data["condition"]}) \n{";
          for (int i = 0; i < struct.subStructs.length; i++) {
            code += "\n\t${getCodeFromStruct(struct.subStructs[i])}";
          }
          code += "\n}";
          return code;
        case StructType.repeat:
          code = "do {";
          for (int i = 0; i < struct.subStructs.length; i++) {
            code += "\n\t${getCodeFromStruct(struct.subStructs[i])}";
          }
          code += "\n}";
          code += "while (${struct.data["condition"]});";
          return code;
        case StructType.function:
          code = "void ${struct.data["name"] ?? ""}() \n{";
          for (int i = 0; i < struct.subStructs.length; i++) {
            code += "\n\t${getCodeFromStruct(struct.subStructs[i])}";
          }
          code += "\n}";
          return code;
        default:
          return "";
      }
    }
    generatedCode += getCodeFromStruct(struct);
    state.fullText = generatedCode;
  }
}


final codePod = NotifierProvider<CodeNotifier, CodeController>((){
  return CodeNotifier();
});

final codeInputPod = NotifierProvider<CodeNotifier, CodeController>((){
  return CodeNotifier();
});