name: Build and Release

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    env:
      CGO_ENABLED: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: 1.23.5
        asset_name: "linux"
        binary_name: "linux"
        project_path:  ./cli/
        goos: linux
        goarch: amd64
  release-mac-arm64:
    name: release mac/arm64
    env:
      CGO_ENABLED: 1
    runs-on: darwin-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: 1.23.5
        asset_name: "mac"
        binary_name: "mac"
        project_path:  ./cli/
        goos: darwin
        goarch: arm64
  release-windows-amd64:
    name: release windows/amd64
    env:
      CGO_ENABLED: 1
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: 1.23.5
        asset_name: "windows.exe"
        binary_name: "windows.exe"
        project_path:  ./cli/
        goos: windows
        goarch: amd64
