name: Build and Release

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.23.5

      - name: Display the version of go that we have installed
        run: go version

      - name: Display the release tag
        run: echo ${{ github.event.release.tag_name }}

      - name: Build the Binary
        env:
          CGO_ENABLED: 1
        run: go build -o ${{matrix.os}} ./cli/

      - name: Upload Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./${{matrix.os}}
          file_glob: true
