name: Flutter CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release-macos:
    name: Build and Release macOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git --branch stable --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Install Node.js and appdmg
        run: |
          brew install node
          npm install -g appdmg

      - name: Install flutter_distributor
        run: |
          dart pub global activate flutter_distributor
          # Add flutter_distributor to the PATH
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Build macOS Release
        run: flutter build macos --release

      - name: Package macOS Release with flutter_distributor
        run: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          flutter_distributor package --platform macos --targets dmg

      - name: Publish to GitHub Releases using flutter_distributor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          flutter_distributor publish \
            --path dist/${{ github.ref_name }}/structogrammar-${{ github.ref_name }}-macos.dmg \
            --targets github \
            --github-repo-owner 'oxelf' \
            --github-repo-name 'structogrammar'