name: Build macOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build macOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git --branch stable --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Create a Tag
        id: tag
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')" # Example tag format
          git tag $TAG
          git push origin $TAG
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build macOS Release
        run: flutter build macos --release

      - name: Create .dmg File
        run: |
          APP_NAME="structogrammar"
          BUILD_DIR="build/macos/Build/Products/Release/$APP_NAME.app"
          DMG_DIR="$GITHUB_WORKSPACE/build/macos/dmg"
          mkdir -p "$DMG_DIR"
          hdiutil create -volname "$APP_NAME" -srcfolder "$BUILD_DIR" -ov -format UDZO "$DMG_DIR/$APP_NAME.dmg"

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-dmg
          path: build/macos/dmg/*.dmg

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/macos/dmg/*.dmg
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}