name: Build Windows Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get
        shell: pwsh

      - name: Build Windows Release
        run: flutter build windows --release
        shell: pwsh

      - name: Package Executable
        shell: pwsh
        run: |
          $BUILD_DIR = "build/windows/runner/Release"
          $DIST_DIR = "build/windows/installer"
          $APP_NAME = "structogrammer"  # Update with your app's name
          
          # Create directory for packaging
          New-Item -Path $DIST_DIR -ItemType Directory -Force
          
          # Copy executable and DLLs
          Copy-Item -Path "$BUILD_DIR/$APP_NAME.exe" -Destination $DIST_DIR
          Copy-Item -Path "$BUILD_DIR/*.dll" -Destination $DIST_DIR
          Copy-Item -Path "$BUILD_DIR/data/*" -Destination "$DIST_DIR/data" -Recurse
          
          # Optional: Create a zip file if needed
          Compress-Archive -Path "$DIST_DIR/*" -DestinationPath "$DIST_DIR/$APP_NAME.zip"

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: build/windows/installer/*.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/installer/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}