name: Build Windows App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get
        shell: pwsh

      - name: Create a Tag
        id: tag
        run: |
          $TAG = "v$(Get-Date -Format 'yyyyMMddHHmmss')"
          git tag $TAG
          git push origin $TAG
          echo "TAG=$TAG" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Build Windows Release
        run: flutter build windows --release
        shell: pwsh

      - name: List Build Directory
        run: Get-ChildItem -Recurse build/windows/runner/Release
        shell: pwsh

      - name: Create Installer
        run: |
          $APP_NAME="structogrammar"
          $BUILD_DIR="build/windows/runner/Release/$APP_NAME.exe"
          $ZIP_DIR="$env:GITHUB_WORKSPACE/build/windows/zip"
          mkdir $ZIP_DIR
          Copy-Item -Path $BUILD_DIR -Destination $ZIP_DIR
          Compress-Archive -Path $ZIP_DIR/$APP_NAME.exe -DestinationPath $ZIP_DIR/$APP_NAME.zip
        shell: pwsh

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: build/windows/zip/*.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/zip/*.zip
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}