name: Build Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Windows App
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git --branch stable --depth 1
          $env:GITHUB_PATH += ";$env:GITHUB_WORKSPACE/flutter/bin"

      - name: Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Create a Tag
        id: tag
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')" # Example tag format
          git tag $TAG
          git push origin $TAG
          echo "TAG=$TAG" >> $env:GITHUB_ENV

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Create Installer
        run: |
          $APP_NAME="YourAppName"
          $BUILD_DIR="build\windows\runner\Release\$APP_NAME.exe"
          $ZIP_DIR="$env:GITHUB_WORKSPACE\build\windows\zip"
          mkdir $ZIP_DIR
          Copy-Item -Path $BUILD_DIR -Destination $ZIP_DIR
          Compress-Archive -Path $ZIP_DIR\$APP_NAME.exe -DestinationPath $ZIP_DIR\$APP_NAME.zip

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: build/windows/zip/*.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/zip/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}