name: Build and Release Windows Installer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Windows Installer
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get
        shell: pwsh

      - name: Create a Tag
        id: tag
        run: |
          $TAG = "v$(Get-Date -Format 'yyyyMMddHHmmss')"
          git tag $TAG
          git push origin $TAG
          echo "TAG=$TAG" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Build Windows Release
        run: flutter build windows --release
        shell: pwsh

      - name: Install Inno Setup
        run: choco install innosetup --yes
        shell: pwsh

      - name: Create Installer
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" windows_installer.iss
        shell: pwsh

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: my_app_installer.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: my_app_installer.exe
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}